# Generated by Django 4.2 on 2025-05-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='card_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='card_number',
        ),
        migrations.AddField(
            model_name='customuser',
            name='stripe_card_brand',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Stripeカードブランド'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stripe_card_exp_month',
            field=models.IntegerField(default=0, verbose_name='Stripeカード有効月'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stripe_card_exp_year',
            field=models.IntegerField(default=0, verbose_name='Stripeカード有効年'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stripe_card_last4',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Stripeカード下４桁'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='StripeカスタマーID'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='StripeサブスクリプションID'),
        ),
    ]
