# Generated by Django 4.2 on 2024-10-09 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='カテゴリー名')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真')),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='店舗名')),
                ('description', models.CharField(max_length=128, verbose_name='説明')),
                ('price', models.CharField(max_length=32, verbose_name='価格帯')),
                ('zip_code', models.CharField(max_length=32, verbose_name='郵便番号')),
                ('address', models.CharField(max_length=128, verbose_name='住所')),
                ('business_time', models.CharField(max_length=64, verbose_name='営業時間')),
                ('close_day_of_week', models.CharField(max_length=32, verbose_name='定休日')),
                ('seats_number', models.CharField(max_length=32, verbose_name='座席数')),
                ('rate', models.FloatField(default=0.0, verbose_name='レート')),
                ('review_num', models.IntegerField(default=0, verbose_name='レビュー数')),
                ('reservation_num', models.IntegerField(default=0, verbose_name='予約数')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.category', verbose_name='カテゴリー')),
            ],
            options={
                'verbose_name_plural': 'Restaurant',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, verbose_name='レート')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='レビュー作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='レビュー更新日時')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.restaurant', verbose_name='レストラン')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': 'Review',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='お気に入り登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='お気に入り更新日時')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.restaurant', verbose_name='レストラン')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': 'Favorite',
            },
        ),
    ]
