# Generated by Django 4.2 on 2024-12-02 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_sales'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name_plural': 'Sales'},
        ),
    ]
