# Generated by Django 4.2 on 2024-12-02 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_sales_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='month',
            field=models.IntegerField(default=0, verbose_name='月'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='year',
            field=models.IntegerField(default=0, verbose_name='年'),
        ),
    ]
