# Generated by Django 4.2 on 2024-12-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_sales_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='price_max',
            field=models.IntegerField(default=5000, verbose_name='最高金額'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='price_min',
            field=models.IntegerField(default=1000, verbose_name='最低金額'),
        ),
    ]
