# Generated by Django 4.2 on 2024-12-14 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_restaurant_price_max_restaurant_price_min'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='price',
        ),
    ]
