# Generated by Django 4.2 on 2025-02-15 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_remove_sales_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'カテゴリー', 'verbose_name_plural': 'カテゴリー'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'お気に入り', 'verbose_name_plural': 'お気に入り'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': '予約', 'verbose_name_plural': '予約'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name': 'レストラン', 'verbose_name_plural': 'レストラン'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'レビュー', 'verbose_name_plural': 'レビュー'},
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name': '売上', 'verbose_name_plural': '売上'},
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='reservation_num',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='review_num',
        ),
    ]
