# Generated by Django 4.2 on 2025-03-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_alter_category_options_alter_favorite_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='close_day_of_week',
            field=models.PositiveIntegerField(default=0, verbose_name='定休日'),
        ),
    ]
