# Generated by Django 4.2 on 2025-03-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_alter_restaurant_close_day_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='close_time',
            field=models.TimeField(default='21:00', verbose_name='閉店時間'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='open_time',
            field=models.TimeField(default='17:00', verbose_name='開店時間'),
        ),
    ]
