# Generated by Django 4.2 on 2025-04-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_restaurant_close_time_restaurant_open_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='business_time',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.TimeField(default='', verbose_name='時間'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='seats_number',
            field=models.PositiveIntegerField(default=10, verbose_name='座席数'),
        ),
    ]
