# Generated by Django 4.2 on 2025-04-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_remove_restaurant_business_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='number_of_people',
            field=models.IntegerField(default='', verbose_name='人数'),
        ),
    ]
